/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/units": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List every datasheet in the corpus
         * @description List the datasheets, ordered by slug.
         *
         *     Returns:
         *         One summary per unit.
         */
        get: operations["list_units_units_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/units/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read one datasheet
         * @description Read a datasheet in full: its profiles, equipment, rules, and options.
         *
         *     Returns:
         *         The datasheet, its troop-type profile resolved and each printed rule
         *         name carrying the entry it resolves to.
         *
         *     Raises:
         *         HTTPException: 404, when no datasheet carries the slug.
         */
        get: operations["read_unit_units__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List every rule entry in the corpus
         * @description List the rule entries, ordered by slug.
         *
         *     Returns:
         *         One summary per entry.
         */
        get: operations["list_rules_rules_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rules/unmodelled": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Report the printed rules the engine does not apply
         * @description Report every rule the corpus prints that never reaches the maths.
         *
         *     Returns:
         *         The report, most-printed first.
         */
        get: operations["list_unmodelled_rules_unmodelled_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rules/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read one rule entry
         * @description Read a rule entry in full: its text, its effects, and what it leaves out.
         *
         *     Returns:
         *         The rule entry.
         *
         *     Raises:
         *         HTTPException: 404, when no entry carries the slug. A rule the corpus
         *             prints without an entry has none to read; ``/rules/unmodelled``
         *             names those.
         */
        get: operations["read_rule_rules__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ArmourGate
         * @description A gate on a piece of armour a model wears — by name, among all it wears.
         *
         *     The ``worn`` peer of :class:`WeaponGate`, and the armour half of the
         *     equipment-in-use axis: Parry's "equipped with ... a shield" asks
         *     ``{name: Shield}``. Two things separate it from the weapon gate, and both
         *     come from the equipment itself. Armour has no family vocabulary — a piece is
         *     only ever its printed name — so ``name`` is the sole property; and a model
         *     wears *several* pieces at once where it holds one weapon, so this is a
         *     :class:`MembershipGate`, satisfied by any piece worn that matches.
         */
        ArmourGate: {
            /** Name */
            name?: string | null;
        };
        /**
         * AttackGate
         * @description A gate on the attack a model is the target of.
         *
         *     The incoming attack, from the defender's side: its ``kind`` (Lion Cloak
         *     fires only ``against ... shooting attacks``), whether it is ``magical``
         *     (Lion Cloak wants non-magical, the reason it does not help against a magical
         *     bow), and whether it is ``flaming`` — carries the Flaming Attacks rule.
         *     Orthogonal facts — a shooting or a close-combat attack may be either.
         *     ``at_long_range`` is a fourth, and a mistake kept for now: see #179 and the
         *     note on the field.
         */
        AttackGate: {
            kind?: components["schemas"]["AttackKind"] | null;
            /** Magical */
            magical?: boolean | null;
            /** Flaming */
            flaming?: boolean | null;
            /** At Long Range */
            at_long_range?: boolean | null;
        };
        /**
         * AttackKind
         * @description The kind of attack a model is the target of — a closed, append-only set.
         *
         *     The rulebook names attacks by kind, and rules gate on the *positive* kind
         *     they care about: Lion Cloak on ``shooting``, Parry on being in close combat.
         *     "Not shooting" is not "close combat" — a spell is neither — so the kind is
         *     categorical, never a boolean. A member joins when a rule needs it (a spell
         *     ``magic`` kind when a magic-attack path exists).
         * @enum {string}
         */
        AttackKind: "close_combat" | "shooting";
        /**
         * AttackMarkEffect
         * @description Classify the attacks the bearer makes: they are Magical, or Flaming.
         *
         *     The vocabulary for the rules that modify no quantity but change what an
         *     attack *is* — "any attack made by a model with this special rule, or
         *     made using a weapon with this special rule, is a 'Magical' attack". The
         *     fact producers consume it when they build the incoming-attack facts a
         *     defender's gates read (Lion Cloak's non-magical armour bonus, a ward's
         *     flame gate), from the striker's unit rules and the profile in use
         *     alike. Self-naming by ``attack`` (the peer of ``add`` / ``reroll`` /
         *     ``grants`` / ``forces``); each model forbids the others' keys.
         */
        AttackMarkEffect: {
            when?: components["schemas"]["When"] | null;
            attack: components["schemas"]["AttackMarks"];
        };
        /**
         * AttackMarks
         * @description The properties a rule stamps on the attacks its bearer makes.
         *
         *     One optional flag per property of the incoming-attack facts a defender's
         *     gates read (:class:`AttackGate`, ``kind`` excepted — what kind an attack
         *     is belongs to the phase resolving it, never to a rule). A mark is only
         *     ever conferred: an unmarked attack is already not magical, so a False
         *     here would say nothing and is a data error.
         */
        AttackMarks: {
            /** Magical */
            magical?: boolean | null;
            /** Flaming */
            flaming?: boolean | null;
        };
        /**
         * BarEffect
         * @description The bearer cannot use a piece of armour while this rule is in force.
         *
         *     "A model cannot use a shield alongside a weapon with this special rule
         *     during the Combat phase": a model has two hands, and wielding decides
         *     what else it can hold. The barred piece is *withdrawn* from what the
         *     bearer effectively wears — its armour bonus, whatever its size, and its
         *     presence to any gate that asks — never compensated with a counter-
         *     modifier, which would couple the rule to the piece's printed value.
         *     Consumed where the bearer's usable armour is assembled; scoped by the
         *     weapon in use when the entry rides a weapon profile, as any weapon rule
         *     is. Self-naming by ``bars``; each model forbids the others' keys.
         */
        BarEffect: {
            when?: components["schemas"]["When"] | null;
            /** Bars */
            bars: string;
        };
        /**
         * BaseSize
         * @description Base footprint of a single model, in millimetres.
         */
        BaseSize: {
            /** Width Mm */
            width_mm: number;
            /** Depth Mm */
            depth_mm: number;
        };
        /**
         * BlowEffect
         * @description The rulebook's "X Blow" shape: a triggered strike the foe cannot save.
         *
         *     "If a model with this special rule rolls a natural 6 when making a roll
         *     To Wound for an attack made in combat ... the enemy is not permitted an
         *     armour save (Ward saves can be attempted as normal)": ``denies`` names
         *     the save stages the foe may not attempt on the trigger branch, and
         *     ``slays`` escalates the unsaved wound to the rulebook's Instant Kill
         *     ("loses all of its remaining Wounds") — Killing Blow sets both, Cleaving
         *     Blow denies alone. The ``when`` must carry the natural trigger, on a
         *     roll before the denied stage; that a die must show a face is also what
         *     keeps the printed automatic-wound exception free — an automatic roll
         *     shows no die. Self-naming by ``denies``.
         */
        BlowEffect: {
            when?: components["schemas"]["When"] | null;
            /** Denies */
            denies: components["schemas"]["Stage"][];
            /**
             * Slays
             * @default false
             */
            slays: boolean;
        };
        /**
         * Bounded
         * @description An amount with the printed bound on the value it moves.
         *
         *     The page prints a bound attached to the quantity it bounds, inside the
         *     parenthetical that follows it — "improves its armour value by 1 (to a
         *     maximum of 2+)", "a -1 modifier to their Strength characteristic (to a
         *     minimum of 1)" — so the bound is written on the amount, not beside the
         *     operation. An operation moving two quantities then cannot lend one's
         *     bound to the other.
         *
         *     ``maximum`` is the printed limit on the modified value: a ceiling on a
         *     characteristic, the best attainable save (so numerically a floor) on an
         *     armour value. ``minimum`` is the floor a malus cannot push a
         *     characteristic below; an armour value needs none, its own floor being
         *     what ``maximum`` already names.
         *
         *     Write the amount plainly (``S: -1``) where the page prints no bound —
         *     the long form exists to carry one.
         */
        Bounded: {
            /** Amount */
            amount: number | "X";
            /** Maximum */
            maximum?: number | null;
            /** Minimum */
            minimum?: number | null;
        };
        /**
         * Characteristic
         * @description The profile characteristics; values are the printed abbreviations.
         *
         *     The single declaration of the vocabulary: profile rows are keyed by
         *     it, tests match on it, and rule effects will name it.
         * @enum {string}
         */
        Characteristic: "M" | "WS" | "BS" | "S" | "T" | "W" | "I" | "A" | "Ld";
        /**
         * ChargeGate
         * @description A gate on the charge event — the model's own charge this turn.
         *
         *     The typed home for "a turn in which it charged", carrying the charge's
         *     properties so a rule can constrain them: Furious Charge asks
         *     ``{distance: {at_least: 3}}``. A property name outside this model is a
         *     data error at load (``extra=forbid``), the same closed-vocabulary
         *     discipline the flat conditions have — load-time path validation falls out
         *     of the typed model. New properties (the arc, the number of enemy models
         *     charged) join here as rules need them.
         */
        ChargeGate: {
            distance?: components["schemas"]["Comparison"] | null;
        };
        /**
         * ChoiceEffect
         * @description Force the outcome of a decision that is otherwise rolled or chosen.
         *
         *     ``forces`` maps a :class:`Decision` to the :class:`~avelorn.tow.schema.psychology.Outcome`
         *     it takes instead of rolling — ``{break: fall-back-in-good-order}``. Keyed by
         *     the decision exactly as a modifier's ``add`` is keyed by the quantity, so the
         *     seam that owns a decision reads its own key ("is ``break`` mine, and forced
         *     to what?") with no per-rule handler. The value is typed as the ``Outcome``
         *     base; each decision's own results are a subclass (a break's are
         *     :class:`~avelorn.tow.schema.psychology.BreakOutcome`), resolved by slug, so
         *     this generic effect names no decision. Self-naming by ``forces`` (the peer of
         *     ``add`` / ``grants``); each model forbids the others' keys. Forbidding an
         *     option rather than forcing one is the sibling (a ``forbids`` key) for when
         *     one lands.
         */
        ChoiceEffect: {
            when?: components["schemas"]["When"] | null;
            /** Forces */
            forces: {
                [key: string]: string;
            };
        };
        /**
         * CombatGate
         * @description A gate on the close combat the model is fighting.
         *
         *     Facts of the combat itself, not the model: ``first_round`` (Elven Reflexes,
         *     Martial Prowess), ``outnumbers`` — whether this side's Unit Strength
         *     beats the foe's (Massed Infantry) — and ``was_charged``, whether the foe
         *     charged the bearer this turn (Shieldwall's "a turn in which it was
         *     charged"). Booleans today; the subject is where a round *number* or a
         *     flank/rear facing would join.
         */
        CombatGate: {
            /** First Round */
            first_round?: boolean | null;
            /** Outnumbers */
            outnumbers?: boolean | null;
            /** Was Charged */
            was_charged?: boolean | null;
        };
        /**
         * Comparison
         * @description A predicate on one numeric property of an event: exactly one comparator.
         *
         *     The leaf of a gate path — ``charging.distance`` is constrained by
         *     ``{at_least: 3}``, ``{at_most: 6}`` or ``{equals: 8}``. The comparator
         *     vocabulary is closed and append-only, the same discipline as
         *     :class:`Quantity`; a new one joins when a rule needs it. Exactly one
         *     comparator is set — a leaf tests one thing.
         */
        Comparison: {
            /** Equals */
            equals?: number | null;
            /** At Least */
            at_least?: number | null;
            /** At Most */
            at_most?: number | null;
        };
        /**
         * Decision
         * @description A point where an outcome is rolled or chosen, that a rule may force.
         *
         *     The routing key of a :class:`ChoiceEffect` — the peer of :class:`Quantity`
         *     for a modifier: the seam that owns a decision reads the effects forcing it.
         *     Closed and append-only; a member joins when a rule forces a new decision (a
         *     charge reaction, ...).
         * @enum {string}
         */
        Decision: "break";
        /**
         * DiceQuantity
         * @description A printed quantity decided by a dice roll: "D6", "D3", "D3+1".
         *
         *     The dice form of a rule's bracketed parameter — "Often, this is
         *     determined by the roll of a dice" (Stomp Attacks, Impact Hits). One
         *     die plus a flat addend covers every printed instance; a wider form
         *     (2D6, say) joins when a rule prints one.
         */
        DiceQuantity: {
            /**
             * Sides
             * @enum {integer}
             */
            sides: 3 | 6;
            /**
             * Plus
             * @default 0
             */
            plus: number;
        };
        /**
         * FoeGate
         * @description A gate on the foe of the attack the bearer is making.
         *
         *     The mirror of :class:`AttackGate` — that subject describes the attack a
         *     model *suffers*, this one the model its own attack lands on. Killing
         *     Blow and Cleaving Blow read the foe's troop type ("enemy models whose
         *     troop type is infantry or cavalry ..."): ``troop_type`` is the printed
         *     list, satisfied by any member. A printed category expands to its
         *     sub-types when the entry is authored — the rulebook's own reading
         *     ("when the rules refer to Infantry units, Monstrous Infantry must also
         *     follow", troop-types-at-a-glance) — so the engine matches one closed
         *     vocabulary, never a category tree.
         */
        FoeGate: {
            /** Troop Type */
            troop_type?: components["schemas"]["TroopType"][] | null;
        };
        /**
         * GrantEffect
         * @description Confer a named special rule, gated like any other effect.
         *
         *     "gains the Armour Bane (1) special rule" — the rule is granted *by name*, not
         *     copied: the consuming seam resolves ``grants`` to its entry (the one
         *     resolution convention, parameter substituted) and applies that rule's own
         *     effects under this grant's gate. So a change to the granted rule — or to how
         *     its quantity resolves — is tracked automatically, and a rule granted on top of
         *     one a model already carries stacks (two Armour Bane (1) → +2 on a natural 6),
         *     because each instance is a separate effect. The grant's shared ``when`` is the
         *     *outer* gate; the granted rule keeps its *own* inner gate
         *     (Armour Bane's natural-6 To Wound), the two conjoined at evaluation without
         *     merging the gate trees. There is no discriminator field: an effect carrying
         *     ``grants`` is one, exactly as one carrying ``add`` is a modifier (each model
         *     forbids the others' keys).
         */
        GrantEffect: {
            when?: components["schemas"]["When"] | null;
            /** Grants */
            grants: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HitOrder
         * @description When a rule's extra hits land in a round of close combat.
         *
         *     The two printed timings: ``first`` — "resolved against the charged
         *     unit when the combat is chosen ... before issuing challenges"
         *     (Impact Hits), ahead of every Initiative step — and ``last`` — "must
         *     be made last, after all other attacks have been made, including
         *     attacks made at Initiative 1" (Stomp Attacks). A member joins when a
         *     rule prints a third timing.
         * @enum {string}
         */
        HitOrder: "first" | "last";
        /**
         * HitsEffect
         * @description Extra hits that land automatically, outside the Initiative-ordered blows.
         *
         *     The "X automatic hits" shape Stomp Attacks and Impact Hits share: each
         *     model with the rule causes ``hits`` hits — a number or a
         *     :class:`DiceQuantity`, usually the bracketed parameter — that skip the
         *     Roll to Hit ("they hit automatically") and wound at the unmodified
         *     Strength of the model making them, at the point of the round ``order``
         *     names. Consumed by the combat round, which folds the batch in at that
         *     point, a dice quantity as its exact distribution. Self-naming by
         *     ``hits``; each model forbids the others' keys.
         */
        HitsEffect: {
            when?: components["schemas"]["When"] | null;
            /** Hits */
            hits: number | components["schemas"]["DiceQuantity"] | "X";
            order: components["schemas"]["HitOrder"];
        };
        /**
         * ModifierEffect
         * @description One printed conditional modifier, shaped as the sentence prints it.
         *
         *     "*If* a model rolls a natural 6 when making a roll To Wound, the
         *     Armour Piercing of its weapon is improved by X" — ``when`` holds
         *     the if (a :class:`When` gate), the operation (``add`` / ``set``) holds
         *     the consequence. ``When`` is a typed tree, ``subject -> property``: the
         *     combat's facts, the model's movement, the volley it fires, and the
         *     ``natural`` die event. Every set fact is conjoined; a state fact the
         *     engine cannot answer leaves the whole rule unfactored and reported, one
         *     answered False is honoured by not applying. Without a ``when`` the
         *     modifier applies to every attack. A rule needing branching or ``else``
         *     belongs in a code handler, not this data.
         *
         *     The operation names itself, mirroring how the page prints it. ``add``
         *     is a signed delta the rulebook writes as a modifier — To Hit penalties
         *     negative ("-1 To Hit modifier" is ``add: {to-hit: -1}``), Armour
         *     Piercing improvements positive ("improved by 1" is
         *     ``add: {armour-piercing: 1}``). ``set`` is a replacement the rulebook
         *     writes as prose — "improves its Initiative characteristic to 10" is
         *     ``set: {I: 10}`` — applied before any additive modifier, and honoured
         *     only where a base value is read (the characteristic query and its
         *     siblings); the dice walk and the armour fold, which move a target
         *     rather than replace a base, read ``add`` alone. An effect carries at
         *     least one operation, and both map each quantity to its printed amount.
         *     A quantity is a roll of the attack sequence by its kind (consumed by
         *     the dice walk), a profile characteristic by its printed abbreviation
         *     ("+1 modifier to its Initiative characteristic" is ``add: {I: 1}``,
         *     consumed by the effective-characteristic query), a formation quantity
         *     like the number of fighting ranks (``add: {fighting-ranks: 1}``,
         *     consumed by the fighting-rank query), a combat-result point
         *     (``add: {combat-result: 1}``, summed into the round's score), or an
         *     armour-value improvement (``add: {armour-value: 1}``, folded into the
         *     defender's save), or a ward save at its printed Warding value
         *     ("has a 6+ Ward save" is ``set: {ward-save: 6}``, folded into the
         *     defender's ward — the best of the values granted, since wards never
         *     stack). The literal ``"X"`` means the rule's bracketed
         *     parameter ("the amount shown in brackets after the name of this
         *     special rule").
         *     Where a change lands follows from its quantity, so no stage is spelled
         *     out. Equipment in use is gated in the ``when`` like any other fact — Parry's
         *     "a hand weapon and a shield" is
         *     ``{wielding: {name: Hand Weapon}, worn: {name: Shield}}`` — evaluated against
         *     the loadout the consuming seam has in its context. A printed bound ("to a
         *     maximum of 10", "to a minimum of 1") is written on the amount it bounds, as
         *     a :class:`Bounded` — ``add: {S: {amount: -1, minimum: 1}}`` — never beside
         *     the operation, where an effect moving two quantities could not say which
         *     one it bounds. Only an ``add`` takes a bound: the page prints bounds on
         *     modifiers, and a ``set`` names the value outright.
         *
         *     ``enemy`` transcribes the printed sentence's subject when it is the
         *     other party: "enemy units ... suffer a -1 To Hit modifier" moves the
         *     *enemy's* To Hit, where the default (the page speaks of the bearer)
         *     moves the bearer's own. Whose quantity it then is in a given attack
         *     follows from the quantity's owner side — the rulebook's constant,
         *     never authored — flipped by this word: a bearer's ``to-hit`` shapes
         *     the attacks it makes, an enemy's the attacks it suffers. Two seams
         *     resolve the flip today: the dice walk (roll quantities), and the
         *     effective-characteristic query, which folds the *foe's* enemy-subject
         *     operations beside the bearer's own wherever both sides are in hand
         *     ("enemy models suffer a -1 modifier to their Strength characteristic",
         *     "enemy models become subject to ... Strike Last"). Every other seam
         *     folds a side's own values, so ``enemy`` there is a data error until a
         *     printed rule needs it.
         */
        ModifierEffect: {
            when?: components["schemas"]["When"] | null;
            /** Add */
            add?: {
                [key: string]: number | "X" | components["schemas"]["Bounded"];
            } | null;
            /** Set */
            set?: {
                [key: string]: number | "X";
            } | null;
            /**
             * Enemy
             * @default false
             */
            enemy: boolean;
        };
        /**
         * MovementGate
         * @description A gate on how the model moved this turn.
         *
         *     ``moved`` is any move (Moving and Shooting's To Hit penalty); ``charge`` is
         *     the charge — ``false`` to require the model did not charge (Press of Battle,
         *     Fight in Extra Rank), or a :class:`ChargeGate` to constrain the charge's
         *     properties (Furious Charge's ``{distance: {at_least: 3}}``).
         */
        MovementGate: {
            /** Moved */
            moved?: boolean | null;
            /** Charge */
            charge?: boolean | components["schemas"]["ChargeGate"] | null;
        };
        /**
         * NaturalRoll
         * @description A natural face shown by one of the attack sequence's dice.
         *
         *     The *event* half of the trigger vocabulary — "rolls a natural 6
         *     when making a roll To Wound". Where ``when`` gates on engagement
         *     state, known once before any die is cast (and possibly unknown),
         *     an event is decided branch by branch during resolution and is never
         *     unknown. ``roll`` must name a stage that rolls one die per attack —
         *     the stage's own :attr:`~avelorn.tow.schema.stage.Stage.dice` row,
         *     checked at data load.
         */
        NaturalRoll: {
            /** Face */
            face: number;
            roll: components["schemas"]["Stage"];
        };
        /**
         * OptionKind
         * @description Coarse category of a unit option.
         * @enum {string}
         */
        OptionKind: "champion" | "standard_bearer" | "musician" | "equipment" | "special_rule" | "magic_standard" | "other";
        /**
         * PanicCause
         * @description Why a panic test was forced, named as the sections are printed.
         * @enum {string}
         */
        PanicCause: "heavy-casualties" | "nearby-friend-destroyed" | "nearby-friend-flees-combat" | "fled-through";
        /**
         * PrintedRule
         * @description A rule name as a datasheet prints it, and the entry it resolves to.
         *
         *     ``slug`` addresses the entry, so a caller can link to it without knowing
         *     how a printed name finds its file -- an exact match, or the "(X)" template
         *     a parameterised name comes from ("Impact Hits (D3)" is filed under
         *     ``impact-hits``). ``None`` says the corpus prints this name and nothing
         *     models it: the fact :func:`unmodelled_rules` reports over the whole corpus,
         *     said here on the datasheet that prints it.
         */
        PrintedRule: {
            /** Name */
            name: string;
            /** Slug */
            slug: string | null;
        };
        /**
         * Profile
         * @description One row of a characteristic profile, keyed by the printed abbreviations.
         *
         *     A unit may have several rows, e.g. rank-and-file plus champion. The
         *     row is written flat in the printed form ({ name: ..., M: 5, ... });
         *     a validator gathers the abbreviation keys into ``characteristics``,
         *     so the vocabulary is declared once, on :class:`Characteristic`.
         *
         *     ``role`` says which part of the model the row describes
         *     (:class:`ProfileRole`); it defaults to rank-and-file, which is what a
         *     single-row datasheet prints.
         */
        Profile: {
            /** Name */
            name: string;
            /** @default rank-and-file */
            role: components["schemas"]["ProfileRole"];
            /** Characteristics */
            characteristics: {
                [key: string]: number | null;
            };
        };
        /**
         * ProfileRole
         * @description What a profile row is a row *of*.
         *
         *     A datasheet's rows are not alternatives; they are the parts a model is made
         *     of. A Silver Helm prints three: the rider, the champion who replaces one
         *     rider, and the Barded Elven Steed every rider sits on. Reading any one of
         *     them as "the unit's profile" drops the others.
         *
         *     The distinction is not cosmetic. A champion is one model of the unit
         *     fighting at its own line (#46); a mount is carried by *every* model and
         *     fights alongside it, contributing its own attacks and lending the ridden
         *     model its Movement. Which row is which cannot be inferred safely at the
         *     point of use -- a mount is recognisable only by the shape of its dashes --
         *     so it is recorded here, once, when the datasheet is written.
         * @enum {string}
         */
        ProfileRole: "rank-and-file" | "champion" | "mount";
        /**
         * Quantity
         * @description A quantity a modifier can change, in the rulebook's own modifier vocabulary.
         *
         *     The whole modifier vocabulary in one closed, append-only enum — a member
         *     joins when an imported rule needs it. Each member knows the :class:`Seam`
         *     that consumes it, so routing is the member's own knowledge, not a side
         *     table: ``to-hit`` and ``armour-piercing`` land on the dice walk,
         *     ``fighting-ranks`` / ``supporting-ranks`` on the fighting-rank query,
         *     ``combat-result`` on the combat-result fold, and ``armour-value`` on the
         *     armour fold (a defender improving its own save). A profile
         *     :class:`~avelorn.tow.schema.unit.Characteristic` is the one quantity kept
         *     apart — a stat vocabulary used far beyond modifiers — so an operation's
         *     key is a Quantity or a Characteristic.
         * @enum {string}
         */
        Quantity: "to-hit" | "armour-piercing" | "fighting-ranks" | "supporting-ranks" | "combat-result" | "armour-value" | "ward-save";
        /**
         * ReplaceEffect
         * @description Replace one of a decision's outcomes with another, leaving the rest rolled.
         *
         *     The sibling of :class:`ChoiceEffect` for a choice narrower than the whole
         *     decision: Shieldwall's "may Give Ground rather than Fall Back in Good
         *     Order" takes effect only where the Break test would have resolved Fall
         *     Back — the Breaks and Gives Ground slices roll as ever, where a *forced*
         *     decision sends the whole mass one way. ``replaces`` maps the decision to
         *     ``{outcome replaced: outcome taken}``, each resolved by slug against the
         *     decision's own outcome set, exactly as ``forces`` values are.
         *     Self-naming by ``replaces``; each model forbids the others' keys.
         */
        ReplaceEffect: {
            when?: components["schemas"]["When"] | null;
            /** Replaces */
            replaces: {
                [key: string]: {
                    [key: string]: string;
                };
            };
        };
        /**
         * RerollEffect
         * @description Re-roll a test, under the printed re-roll rules.
         *
         *     The re-roll operation, named by its own key — ``reroll: <stage>``, the
         *     self-naming peer of ``add`` and ``set`` (spelled without a hyphen so it is
         *     a plain field, no alias). The operation *is* the key; its value is the test
         *     re-rolled, and the seam owning that stage consumes the grant directly (an
         *     attack roll by the dice walk, a panic test by the fold). A re-roll happens
         *     at most once whatever its source ("no single dice can be re-rolled more than
         *     once, regardless of the source"), and a multi-dice roll re-rolls all its
         *     dice. There is no discriminator field: an effect that carries ``reroll`` is
         *     one, exactly as one carrying ``add`` is a modifier (both models forbid the
         *     other's keys).
         *
         *     A grant is restricted to the part of the roll it names, and which
         *     restriction is legal depends on the stage's seam. ``causes`` restricts
         *     a panic-test re-roll to specific panic causes (Valour of Ages re-rolls
         *     only heavy casualties and fled through); empty means any cause.
         *     ``on_natural`` restricts an attack-roll re-roll to the dice showing that
         *     natural face (Ithilmar Weapons re-rolls rolls To Hit of a natural 1);
         *     None re-rolls every covered die at the stage. The two restrictions are
         *     mutually exclusive — a panic test shows no natural face, an attack roll
         *     has no panic cause — so each belongs to its own seam's stages.
         *
         *     ``of`` is the printed result restriction: which dice the grant covers,
         *     ``failed`` (the default — "may re-roll failed rolls To Hit", and the
         *     only re-roll a rational bearer takes of its own dice) or ``successful``
         *     ("must re-roll successful Armour Saves" — a re-roll imposed on the
         *     roller). ``enemy`` transcribes the sentence's subject when the roller
         *     is the other party: "*Enemy units* must re-roll ..." names the enemy's
         *     die, where the default names the bearer's own. Whose die a stage rolls
         *     is the sequence's constant (:attr:`~avelorn.tow.schema.stage.Stage.rolled_by`),
         *     so the seat a grant applies from follows — an enemy-subject save
         *     re-roll fires on the attacks the bearer *makes*, a bearer-subject one
         *     on the attacks it suffers. Both restrictions name a single die's
         *     result or face, so they cover only stages rolling one die per attack.
         */
        RerollEffect: {
            when?: components["schemas"]["When"] | null;
            reroll: components["schemas"]["Stage"];
            /** Causes */
            causes?: components["schemas"]["PanicCause"][];
            /** On Natural */
            on_natural?: number | null;
            /** @default failed */
            of: components["schemas"]["RollResult"];
            /**
             * Enemy
             * @default false
             */
            enemy: boolean;
        };
        /**
         * RollResult
         * @description One die's result, in the printed re-roll vocabulary.
         *
         *     The rulebook restricts a re-roll by the result of the dice it names:
         *     "may re-roll *failed* rolls To Hit", "must re-roll *successful*
         *     Armour Saves". Transcribed as printed; the walk re-rolls exactly the
         *     dice the word covers, with no assumption about whom the re-roll
         *     serves.
         * @enum {string}
         */
        RollResult: "failed" | "successful";
        /**
         * Rule
         * @description A rules-page entry (special rule or core rule), text verbatim.
         */
        Rule: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Page */
            page?: number | null;
            /** Category */
            category?: string | null;
            /** Flavour */
            flavour?: string | null;
            /** Paragraphs */
            paragraphs: string[];
            /** Effects */
            effects?: (components["schemas"]["ModifierEffect"] | components["schemas"]["RerollEffect"] | components["schemas"]["GrantEffect"] | components["schemas"]["ChoiceEffect"] | components["schemas"]["AttackMarkEffect"] | components["schemas"]["BarEffect"] | components["schemas"]["BlowEffect"] | components["schemas"]["WoundMultiplierEffect"] | components["schemas"]["VolleyEffect"] | components["schemas"]["ReplaceEffect"] | components["schemas"]["HitsEffect"])[];
            /** Notes */
            notes?: string | null;
        };
        /**
         * RuleSummary
         * @description A rule entry as a listing shows it: what it is, and whether it reaches the maths.
         *
         *     ``factors`` is the honest bit. An entry carries effects or it does not, and
         *     one that does not is text the engine holds and never applies -- Killing Blow
         *     is the standing example, its "no armour save allowed" having no word in the
         *     effect vocabulary. ``references`` counts the units and weapons printing it,
         *     so a listing sorts by what would matter most to model next.
         */
        RuleSummary: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Category */
            category: string | null;
            /** Factors */
            factors: boolean;
            /** References */
            references: number;
        };
        /**
         * ShootingGate
         * @description A gate on the volley the model is firing.
         *
         *     ``at_long_range`` is whether the target sits beyond half the weapon's
         *     maximum range (Firing at Long Range); ``stand_and_shoot`` whether the
         *     volley is a Stand & Shoot charge reaction (which Volley Fire forbids).
         *     The subject is where a range band or a cover fact would join.
         */
        ShootingGate: {
            /** At Long Range */
            at_long_range?: boolean | null;
            /** Stand And Shoot */
            stand_and_shoot?: boolean | null;
        };
        /**
         * Stage
         * @description The attack sequence's stages, one row per printed step.
         *
         *     Each member is a row of the printed sequence: its name (verbatim),
         *     ``rolled_by`` (whose dice the stage rolls — the attacker's To Hit and
         *     To Wound, the target's saves and panic tests), and ``dice`` (what is
         *     rolled there). Declaration order is the printed order — the engine's
         *     "can this die still shape that roll" reads it directly.
         * @enum {string}
         */
        Stage: "roll-to-hit" | "roll-to-wound" | "make-armour-saves" | "ward-saves" | "make-panic-tests";
        /**
         * TroopType
         * @description Closed set from the rulebook's troop-type table.
         * @enum {string}
         */
        TroopType: "Regular Infantry" | "Heavy Infantry" | "Monstrous Infantry" | "Swarm" | "Light Cavalry" | "Heavy Cavalry" | "Monstrous Cavalry" | "War Beast" | "Light Chariot" | "Heavy Chariot" | "Monstrous Creature" | "Behemoth" | "War Machine";
        /**
         * TroopTypeProfile
         * @description A troop type's rank-and-file data, and how it ranks up.
         *
         *     ``models_per_rank`` is how many models a rank must hold to count
         *     toward the Rank Bonus, or None for a troop type that does not rank up
         *     (Swarm, Heavy Chariot, the monsters and war machines that fight as
         *     single models); ``max_rank_bonus`` is the most extra ranks it may
         *     claim. ``unit_strength`` is each model's Unit Strength as the
         *     troop-type table prints it — a fixed count, or "As Starting Wounds"
         *     for the troop types whose strength scales with the model.
         *     ``special_rules`` are the rules the troop type confers on every
         *     unit of it (Regular Infantry's Press of Battle, say), as printed
         *     display-name strings — the type's own rules, held apart from the
         *     datasheet's ``special_rules`` because their owner is the troop type,
         *     not the unit.
         */
        TroopTypeProfile: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            unit_strength: components["schemas"]["UnitStrength"];
            /** Models Per Rank */
            models_per_rank?: number | null;
            /**
             * Max Rank Bonus
             * @default 0
             */
            max_rank_bonus: number;
            /**
             * Special Rules
             * @default []
             */
            special_rules: string[];
        };
        /**
         * UnitDetail
         * @description A datasheet as reading one shows it: the entry, its rule names resolved.
         *
         *     Everything :class:`~avelorn.tow.schema.unit.Unit` prints, except that a
         *     special rule arrives as a :class:`PrintedRule` rather than a bare string.
         *     Resolving on the way out is what keeps a caller from re-deriving it: a
         *     printed name does not become a slug by slugifying it.
         */
        UnitDetail: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Points */
            points: number;
            unit_size: components["schemas"]["UnitSize"];
            troop_type: components["schemas"]["TroopType"];
            troop_type_profile?: components["schemas"]["TroopTypeProfile"] | null;
            base_size?: components["schemas"]["BaseSize"] | null;
            /** Profiles */
            profiles: components["schemas"]["Profile"][];
            /** Equipment */
            equipment?: string[];
            /** Special Rules */
            special_rules: components["schemas"]["PrintedRule"][];
            /** Options */
            options?: components["schemas"]["UnitOption"][];
        };
        /**
         * UnitOption
         * @description A purchasable upgrade.
         *
         *     Exactly one cost shape applies: a flat `points` cost (per unit, or per
         *     model when `per_model` is set) or a `points_budget` to spend up to
         *     (e.g. magic standards).
         */
        UnitOption: {
            /** Name */
            name: string;
            /** @default other */
            kind: components["schemas"]["OptionKind"];
            /** Applies To */
            applies_to?: string | null;
            /** Points */
            points?: number | null;
            /**
             * Per Model
             * @default false
             */
            per_model: boolean;
            /** Points Budget */
            points_budget?: number | null;
            /** Adds Rules */
            adds_rules?: string[];
            /** Removes Rules */
            removes_rules?: string[];
            /** Adds Equipment */
            adds_equipment?: string[];
            /** Removes Equipment */
            removes_equipment?: string[];
            /** Limit */
            limit?: string | null;
        };
        /**
         * UnitSize
         * @description Allowed model count for a unit.
         */
        UnitSize: {
            /** Min */
            min: number;
            /** Max */
            max?: number | null;
        };
        UnitStrength: number | components["schemas"]["UnitStrengthMarker"];
        /**
         * UnitStrengthMarker
         * @description The troop-type table's non-numeric Unit Strength markers.
         *
         *     A closed, append-only vocabulary like the rulebook's other tables: a
         *     member joins when the Unit Strength column prints a new marker in place
         *     of a number. ``STARTING_WOUNDS`` is the table's "W" — the model's Unit
         *     Strength is its starting Wounds, not a fixed count. Each marker names a
         *     distinct resolution, so the troop type must match on the member rather
         *     than lump every non-numeric value together.
         * @enum {string}
         */
        UnitStrengthMarker: "W";
        /**
         * UnitSummary
         * @description A datasheet as a listing shows it: what it costs and how it is fielded.
         */
        UnitSummary: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Points */
            points: number;
            unit_size: components["schemas"]["UnitSize"];
            troop_type: components["schemas"]["TroopType"];
        };
        /**
         * UnmodelledRule
         * @description A rule the corpus prints that has no entry, so the engine cannot apply it.
         *
         *     Keyed by printed ``name``: that is how a datasheet references a rule, and
         *     with no entry it is the only handle the rule has. ``units`` and ``weapons``
         *     name who prints it, which is what makes the report actionable -- a rule
         *     nothing carries is not worth modelling yet.
         *
         *     An entry that carried no effects would be unapplied too, but no such entry
         *     is allowed in ``data/`` (``test_every_rule_entry_carries_effects``): a rule
         *     that cannot fold is filed by not filing it. So a missing entry is the only
         *     way a printed rule goes unmodelled, and this needs no reason field.
         */
        UnmodelledRule: {
            /** Name */
            name: string;
            /** Units */
            units: string[];
            /** Weapons */
            weapons: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VolleyEffect
         * @description Volley Fire's printed mechanic: rear ranks join the volley by halves.
         *
         *     "Half of the models in each rank other than the front rank, rounding
         *     up, can shoot" — a shot-count rule, landing on how many models fire,
         *     never on the dice. The one printed fraction is the closed vocabulary;
         *     a variant joins when a rule prints one. Gated as the page gates it
         *     (no move this turn, never on a Stand & Shoot); the hill variant is
         *     terrain and stays in the entry's notes. Self-naming by ``volley``.
         */
        VolleyEffect: {
            when?: components["schemas"]["When"] | null;
            /**
             * Volley
             * @constant
             */
            volley: "half-of-each-rear-rank";
        };
        /**
         * WeaponGate
         * @description A gate on the weapon a model has in hand — by family or by name.
         *
         *     The typed home for "wielding a bow" / "wielding this weapon": ``type`` names a
         *     weapon family (:class:`~avelorn.tow.schema.weapon.WeaponType`, the seam #107
         *     added), ``name`` a specific printed name. Arrows of Isha asks
         *     ``{type: bow}``; Parry's "a hand weapon" asks ``{name: Hand Weapon}``. Both
         *     may be set (a specific weapon of a family). At least one must be, or the gate
         *     constrains nothing (``extra=forbid`` keeps a stray property a load error).
         */
        WeaponGate: {
            type?: components["schemas"]["WeaponType"] | null;
            /** Name */
            name?: string | null;
        };
        /**
         * WeaponType
         * @description A weapon's family in the Weapons of War chapter — a closed, append-only set.
         *
         *     The rulebook groups weapons into families a rule can speak to as one ("any
         *     bow" — a longbow, shortbow, warbow or the Bow of Avelorn). The source does
         *     not carry the family as a field, and the individual weapon entries do not
         *     name it, so it is hand-authored here. A member joins, and a weapon is
         *     classified, only when a rule needs to gate on the family — the same
         *     just-in-time discipline the rest of the vocabulary follows. Values are slugs,
         *     matching the id convention of rules and weapons, so a future rule specific to
         *     a weapon family can key on the family as it keys on a slug.
         * @enum {string}
         */
        WeaponType: "bow";
        /**
         * When
         * @description An effect's gate: the facts that must hold for it to apply.
         *
         *     A typed tree, one field per subject — the combat the model is engaged in,
         *     its movement, the volley it fires, the attack it is the target of — each
         *     carrying that subject's own facts, plus the ``natural`` dice event. A rule
         *     reads as ``subject -> property (-> comparator)``:
         *     ``{combat: {first_round: true}}``, ``{target_of: {kind: shooting}}``.
         *
         *     ``combat`` and ``target_of`` are presence entities: ``combat: true`` gates
         *     on being engaged in a close combat (Parry's "whilst engaged in close
         *     combat"), a nested gate on being engaged *and* a property (Elven Reflexes's
         *     first round); ``target_of`` names the incoming attack. ``wielding`` and
         *     ``worn`` are the equipment-in-use axis — the weapon a model is acting with
         *     (Arrows of Isha's "any bow", matched by family or name) and the armour it
         *     wears (Parry's shield, matched among every piece worn) — read off the
         *     engagement context by the dice walk and the folds alike, so a rule gates on
         *     its gear exactly as it gates on the engagement. A subject or property outside
         *     these models is a data error at load (``extra=forbid``) — the closed
         *     vocabulary the flat Condition enum gave, now structural. Every set fact is
         *     conjoined; without a ``when`` the modifier applies to every attack.
         */
        When: {
            /** Combat */
            combat?: boolean | components["schemas"]["CombatGate"] | null;
            movement?: components["schemas"]["MovementGate"] | null;
            shooting?: components["schemas"]["ShootingGate"] | null;
            wielding?: components["schemas"]["WeaponGate"] | null;
            worn?: components["schemas"]["ArmourGate"] | null;
            /** Target Of */
            target_of?: boolean | components["schemas"]["AttackGate"] | null;
            foe?: components["schemas"]["FoeGate"] | null;
            natural?: components["schemas"]["NaturalRoll"] | null;
        };
        /**
         * WoundMultiplierEffect
         * @description The rulebook's Multiple Wounds shape: each unsaved wound is multiplied.
         *
         *     "Each unsaved wound inflicted by an attack with this special rule is
         *     multiplied by the number shown in brackets" — ``multiplies`` is that
         *     number: a printed constant, a :class:`DiceQuantity` ("D3", rolled
         *     separately for each unsaved wound, so a distribution and never an
         *     expectation), or the rule's "X" parameter, bound from the bracketed
         *     value exactly as an automatic-hits count is. The printed cap — "excess wounds caused to a
         *     model will have no additional effect", and they "do not 'spill over'
         *     onto other models" — is not authored here: it is the Remove Casualties
         *     fold's own knowledge, where a wound lands on a model with so many
         *     Wounds remaining. Self-naming by ``multiplies``; each model forbids
         *     the others' keys.
         */
        WoundMultiplierEffect: {
            when?: components["schemas"]["When"] | null;
            /** Multiplies */
            multiplies: number | components["schemas"]["DiceQuantity"] | "X";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_units_units_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnitSummary"][];
                };
            };
        };
    };
    read_unit_units__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnitDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rules_rules_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleSummary"][];
                };
            };
        };
    };
    list_unmodelled_rules_unmodelled_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnmodelledRule"][];
                };
            };
        };
    };
    read_rule_rules__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rule"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
